/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySensor.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySensor (1 custom class methods, 1 custom properties)

#import "GTLQuerySensor.h"

#import "GTLSensorData.h"

@implementation GTLQuerySensor

@dynamic fields;

#pragma mark - "data" methods
// These create a GTLQuerySensor object.

+ (instancetype)queryForDataCreateWithObject:(GTLSensorData *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"sensor.data.create";
  GTLQuerySensor *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLSensorData class];
  return query;
}

@end
