/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQuerySensor.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API
// Classes:
//   GTLQuerySensor (1 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLSensorData;

@interface GTLQuerySensor : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

#pragma mark - "data" methods
// These create a GTLQuerySensor object.

// Method: sensor.data.create
//  Authorization scope(s):
//   kGTLAuthScopeSensorUserinfoEmail
// Fetches a GTLSensorData.
+ (instancetype)queryForDataCreateWithObject:(GTLSensorData *)object;

@end
