/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSensorConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API

#import "GTLSensorConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSensorUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
