/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSensorItem.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API
// Classes:
//   GTLSensorItem (0 custom class methods, 7 custom properties)

#import "GTLSensorItem.h"

// ----------------------------------------------------------------------------
//
//   GTLSensorItem
//

@implementation GTLSensorItem
@dynamic dateLastOrdered, ean, imageURL, mass, price, productName,
         userDefinedName;
@end
