/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSensor.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API

#import "GTLSensorConstants.h"

#import "GTLSensorData.h"
#import "GTLSensorItem.h"

#import "GTLQuerySensor.h"
#import "GTLServiceSensor.h"
