/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSensorItem.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API
// Classes:
//   GTLSensorItem (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLSensorItem
//

@interface GTLSensorItem : GTLObject
@property (nonatomic, retain) GTLDateTime *dateLastOrdered;
@property (nonatomic, copy) NSString *ean;
@property (nonatomic, copy) NSString *imageURL;
@property (nonatomic, retain) NSNumber *mass;  // doubleValue
@property (nonatomic, copy) NSString *price;
@property (nonatomic, copy) NSString *productName;
@property (nonatomic, copy) NSString *userDefinedName;
@end
