/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLSensorData.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API
// Classes:
//   GTLSensorData (0 custom class methods, 4 custom properties)

#import "GTLSensorData.h"

#import "GTLSensorItem.h"

// ----------------------------------------------------------------------------
//
//   GTLSensorData
//

@implementation GTLSensorData
@dynamic dateTime, hubId, identifier, items;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"identifier" : @"id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLSensorItem class]
  };
  return map;
}

@end
