/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceSensor.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sensor/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceSensor (0 custom class methods, 0 custom properties)

#import "GTLSensor.h"

@implementation GTLServiceSensor

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQuerySensor class],
    [GTLSensorData class],
    [GTLSensorItem class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://smart-container-1203.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
